### ISSUE TITLE
Consistent capitalization and spelling of Admail

### ISSUE THREAD

**Issue by quiddle** [AdmailDotNet/admail#1]
When the Admail company name is used, there should not be any inner capitalization (i.e. "AdMail").

There are also two typos of "AdNail" that should be update.
[First](https://github.com/AdmailDotNet/admail/blob/674f83726beac14ebb0f9be6b5471d926a570729/admail.php#L155)
[Second](https://github.com/AdmailDotNet/admail/blob/674f83726beac14ebb0f9be6b5471d926a570729/admail.php#L183)

Correct instances of "Admail.org" to "Admail.net".
[First](https://github.com/AdmailDotNet/admail/blob/674f83726beac14ebb0f9be6b5471d926a570729/admail.php#L156)
[Second](https://github.com/AdmailDotNet/admail/blob/674f83726beac14ebb0f9be6b5471d926a570729/admail.php#L184)

**Comment by MGParisi** [comment]
Finished
